# Generated by Django 5.1.2 on 2024-12-15 17:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

def set_default_user(apps, schema_editor):
    Task = apps.get_model('todo', 'Task')
    User = apps.get_model('auth', 'User')
    default_user = User.objects.filter(is_superuser=True).first()  # 使用超级管理员作为默认用户
    for task in Task.objects.filter(user__isnull=True):
        task.user = default_user
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_created_at_task_priority_task_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, blank=True, to='auth.User', on_delete=models.CASCADE),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_user),
    ]
